### ISSUE TITLE
NullPointerException && InflateException

### ISSUE THREAD

**Issue by RakeshSiddu** [davidmigloz/drag-to-close#15]
Caused by: android.view.InflateException: Binary XML file line #0: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
                                                                  

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference

**Comment by davidmigloz** [comment]
Hi Rakesh, 
Thank you for reporting. 
Can you send me the complete stacktrace? or some more info..
I cannot see the source of the problem in what you posted.
Thanks!

**Comment by RakeshSiddu** [comment]
Hi David,
Thank you for your reply.

Issue was with "drag:draggableContainer="@+id/card" in which i didnt mention the layout id to drag. Later i cleared it.
I wanted to know is there a way to drag the container from bottom to top.!!
Thanks

**Comment by davidmigloz** [comment]
Ok, nice that you made it work. I'll try to improve the error handling to give a more meaningful error message.

About dragging from bottom to top, it's not supported yet (#8). If you want to implement it I'd really appreciate your pull request ;).

Thanks!
