### ISSUE TITLE
The current version is wrong in the README

### ISSUE THREAD

**Issue by makhosravi** [davidmigloz/drag-to-close#18]
hi

i have added

Step 1
Add the JitPack repository to your build.gradle file:

allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}
Step 2
Add the dependency:

dependencies {
	implementation 'com.github.davidmigloz:drag-to-close:1.0'
}

but after gradle syncing it shows an error

Failed to resolve: com.github.davidmigloz:drag-to-close:1.0

whats the problem?

**Comment by davidmigloz** [comment]
Hi makhosravi!

Thanks for reporting. The current version in the README code is wrong. 

The right one is `0.1`:

```gradle
dependencies {
	implementation 'com.github.davidmigloz:drag-to-close:0.1'
}
```

I'll fix it right now. Sorry about that.

Regards,
David
