### ISSUE TITLE
Add container  to draggableView

### ISSUE THREAD

**Issue by dhavaljivani** [davidmigloz/drag-to-close#26]
I have added container view to **dragtoclose_draggableView** it's working drag top to bottom but If my container contain **nested scroll view** then I scroll to bottom and then try to scroll to the top then scrolling is not working and my view started dragging 
Can you please suggest me the solution?

**Comment by davidmigloz** [comment]
We have that use case in our app as well and it is working fine. If it's still an issue, could you provide some code? Thanks.
For now, I'll close the issue.
